# Generated by Django 4.2.3 on 2023-07-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Types')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500, verbose_name='Summary')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('time_of_create', models.TimeField(auto_now_add=True, verbose_name='Time of Creation')),
                ('update_time', models.TimeField(auto_now=True, verbose_name='Update time')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issue_tracker.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issue_tracker.types')),
            ],
        ),
    ]
