# Generated by Django 4.2.3 on 2023-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_of_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
    ]
