# Generated by Django 4.2.3 on 2023-07-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_alter_task_time_of_create_alter_task_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.PROTECT, to='issue_tracker.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default='Task', on_delete=django.db.models.deletion.PROTECT, to='issue_tracker.types'),
        ),
    ]
